version: 2
jobs:
  build:
    docker:
      - image: circleci/node

    steps:
      - checkout

      - run:
          name: npm install
          command: npm i

      - run:
          name: npm build
          command: npm run build

  deploy:
    docker:
      - image: circleci/node

    steps:
      - checkout

      - run:
          name: npm install
          command: npm i

      - run:
          name: npm build
          command: npm run build

      - run:
          name: Copy result files to temporary directory
          command: |
            set -xu
            mkdir -p /tmp/artifacts
            cp index.html /tmp/artifacts/
            cp -r build /tmp/artifacts/

      # Save artifacts
      - store_artifacts:
          path: /tmp/artifacts
          destination: build

      - run:
          name: Push gh-pages
          command: |
            if [ "${CIRCLE_BRANCH}" = "master" ]; then
              ./deploy.sh
            fi

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy:
        requires:
          - build
        filters:
          branches:
            only: master
