version: 2
jobs:
  build:
    docker:
      - image: node:10.16.1-alpine

    steps:
      - checkout

      - run:
        name: npm install
        command: npm i

      - run:
          name: npm build
          command: npm run build
